### ISSUE TITLE
disCoverage does create .bed file but no other output

### ISSUE THREAD

**Issue by paulauitt2** [javiercguard/disCoverage#2]
Hi,

When I run disCoverage it successfully generates a bed files with the duplications and deletions I expect from the vcf file, but no other output. The only output line that I get is: 'False False'.

Is there anything that I can do to run disCoverage successfully? 

Best wishes,
Paula Uittenbogaard

**Comment by javiercguard** [comment]
Hi,
I have found the problem, and will fix it in a few days.

**Comment by javiercguard** [comment]
Hi, it works now.
Also please be sure to check the updated README.md and follow the installation the instructions.

**Comment by paulauitt2** [comment]
Thanks! It works perfectly fine for me now.

**Comment by javiercguard** [comment]
Perfect, if you find new problems/questions, feel free to open a new issue.
